spring:
  application:
    name: analyzer

  datasource:
    url: jdbc:postgresql://localhost:5436/stats
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: localhost:9092
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

logging:
  level:
    ru.practicum.service.UserRecommendationsService: DEBUG
    ru.practicum.service.SimilarEventsService: DEBUG
    ru.practicum.service.InteractionsCountService: DEBUG
    ru.practicum.kafka.consumer.UserActionsConsumer: DEBUG
    ru.practicum.kafka.consumer.EventsSimilarityConsumer: DEBUG

