services:
  event-service-db:
      image: postgres:16.1
      container_name: event-service-db
      ports:
        - "5434:5432"
      environment:
        - POSTGRES_PASSWORD=100
        - POSTGRES_USER=admin
        - POSTGRES_DB=event-service-db

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=100
      - POSTGRES_USER=admin
      - POSTGRES_DB=stats-db

  user-service-db:
    image: postgres:16.1
    container_name: user-service-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=user-service-db

  request-service-db:
    image: postgres:16.1
    container_name: request-service-db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=request-service-db

  comment-service-db:
    image: postgres:16.1
    container_name: comment-service-db
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=comment-service-db

