services:
  common-db:
    image: postgres:16.1
    container_name: common-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 100
      POSTGRES_DB: postgres
    volumes:
      - common-db-data:/var/lib/postgresql/data
      - ./init/common-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 100
      POSTGRES_DB: stats-db
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d stats-db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  common-db-data:
  stats-db-data:
